import Vue from 'vue'
import 'element-ui/lib/theme-chalk/index.css';
import { 
    Button,
    Container,
    Header,
    Aside,
    Main,
    Autocomplete,
    Menu,
    MenuItem,
    MenuItemGroup,
    Submenu,
    Popover,
    Input,
    Dropdown,
    DropdownMenu,
    DropdownItem,
    Avatar,
    Row,
    Col,
    Card,
    Form,
    FormItem,
    Select,
    Option,
    Checkbox,
    CheckboxGroup,
    Link,
    Table,
    Collapse,
    CollapseItem,
    TableColumn,
    Breadcrumb,
    BreadcrumbItem,
    Tag,
    Pagination,
    Dialog,
    Popconfirm,
    RadioGroup,
    Radio,
    Switch,
    ButtonGroup,
    Tree,
    MessageBox,
    Message,
    Drawer,
    DatePicker,
    ColorPicker,
    Tabs,
    TabPane
} from 'element-ui'

Vue.use(Popover)
Vue.use(Button)
Vue.use(Tabs)
Vue.use(TabPane)
Vue.use(ColorPicker)
Vue.use(DatePicker)
Vue.use(Drawer)
Vue.use(Collapse)
Vue.use(CollapseItem)
Vue.use(CheckboxGroup)
Vue.use(Autocomplete)
Vue.use(RadioGroup)
Vue.use(Radio)
Vue.use(Switch)
Vue.use(Container)
Vue.use(Header)
Vue.use(Aside)
Vue.use(Main)
Vue.use(Menu)
Vue.use(MenuItem)
Vue.use(MenuItemGroup)
Vue.use(Submenu)
Vue.use(Dropdown)
Vue.use(Input)
Vue.use(DropdownMenu)
Vue.use(DropdownItem)
Vue.use(Avatar)
Vue.use(Row)
Vue.use(Col)
Vue.use(Card)
Vue.use(Form)
Vue.use(FormItem)
Vue.use(Select)
Vue.use(Option)
Vue.use(Checkbox)
Vue.use(Link)
Vue.use(Table)
Vue.use(TableColumn)
Vue.use(Breadcrumb)
Vue.use(BreadcrumbItem)
Vue.use(Tag)
Vue.use(Pagination)
Vue.use(Dialog)
Vue.use(Popconfirm)
Vue.use(ButtonGroup)
Vue.use(Tree)


Vue.prototype.$confirm = MessageBox.confirm
Vue.prototype.$message = Message